from func1 import grams_to_ounces
from func2 import fahrenheit_to_celsius
from func3 import solve
from func4 import filter_prime
from func5 import string_permutations
from func6 import reverse_sentence
from func7 import has_33
from func8 import spy_game
from func9 import sphere_volume
from func10 import unique_elements
from func11 import is_palindrome
from func12 import histogram
from func13 import guess_the_number
